-- V4__seed_top_25_assets.sql
-- Seed the top 25 stocks and top 25 cryptocurrencies for the Market Data tab.

INSERT INTO supported_symbols (symbol, type, api_source, active, base_currency)
VALUES
    -- Top Stocks
    ('AAPL',  'STOCK', 'finnhub', true, 'USD'),
    ('MSFT',  'STOCK', 'finnhub', true, 'USD'),
    ('GOOGL', 'STOCK', 'finnhub', true, 'USD'),
    ('AMZN',  'STOCK', 'finnhub', true, 'USD'),
    ('NVDA',  'STOCK', 'finnhub', true, 'USD'),
    ('META',  'STOCK', 'finnhub', true, 'USD'),
    ('TSLA',  'STOCK', 'finnhub', true, 'USD'),
    ('LLY',   'STOCK', 'finnhub', true, 'USD'),
    ('JPM',   'STOCK', 'finnhub', true, 'USD'),
    ('V',     'STOCK', 'finnhub', true, 'USD'),
    ('UNH',   'STOCK', 'finnhub', true, 'USD'),
    ('XOM',   'STOCK', 'finnhub', true, 'USD'),
    ('MA',    'STOCK', 'finnhub', true, 'USD'),
    ('JNJ',   'STOCK', 'finnhub', true, 'USD'),
    ('PG',    'STOCK', 'finnhub', true, 'USD'),
    ('HD',    'STOCK', 'finnhub', true, 'USD'),
    ('AVGO',  'STOCK', 'finnhub', true, 'USD'),
    ('MRK',   'STOCK', 'finnhub', true, 'USD'),
    ('ABBV',  'STOCK', 'finnhub', true, 'USD'),
    ('CVX',   'STOCK', 'finnhub', true, 'USD'),
    ('KO',    'STOCK', 'finnhub', true, 'USD'),
    ('PEP',   'STOCK', 'finnhub', true, 'USD'),
    ('COST',  'STOCK', 'finnhub', true, 'USD'),
    ('WMT',   'STOCK', 'finnhub', true, 'USD'),
    ('NFLX',  'STOCK', 'finnhub', true, 'USD'),

    -- Top Cryptocurrencies
    ('BINANCE:BTCUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:ETHUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:BNBUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:SOLUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:XRPUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:ADAUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:DOGEUSDT', 'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:AVAXUSDT', 'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:SHIBUSDT', 'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:DOTUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:TRXUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:LINKUSDT', 'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:MATICUSDT','CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:BCHUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:NEARUSDT', 'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:LTCUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:ICPUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:UNIUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:APTUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:XLMUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:ATOMUSDT', 'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:ARBUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:STXUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:INJUSDT',  'CRYPTO', 'finnhub', true, 'USD'),
    ('BINANCE:OPUSDT',   'CRYPTO', 'finnhub', true, 'USD')
ON CONFLICT (symbol) DO NOTHING;
