spring:
  application:
    name: ai-advisor-service
  config:
    import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"
  cloud:
    config:
      fail-fast: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:${KEYCLOAK_ISSUER_URI:http://keycloak:8080/realms/fin-insight}}
          secondary-issuer-uri: ${JWT_SECONDARY_ISSUER_URI:${KEYCLOAK_SECONDARY_ISSUER_URI:http://localhost:8080/realms/fin-insight}}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:${EUREKA_URL:http://localhost:8761/eureka/}}

management:
  endpoints:
    web:
      exposure:
        include: health,info
